### ISSUE TITLE
Won't install on TeamCity 2024.03 (build 156166)

### ISSUE THREAD

**Issue by rickgomes-catapult** [OctopusDeploy/opentelemetry-teamcity-plugin#264]
Build version of Java isn't compatible with Java version packaged with TeamCity. Built using 17 seems like TeamCity is on 8?

**Comment by matt-richardson** [comment]
Interestingly, it works for us on 2024.03:

![image](https://github.com/OctopusDeploy/opentelemetry-teamcity-plugin/assets/373389/63d8c813-f64d-4334-a60f-f01e7e3c3bc3)

How are you hosting TC?

**Comment by matt-richardson** [comment]
(we're using the "jetbrains/teamcity-server" container)

**Comment by matt-richardson** [comment]
That container appears to use java 17: https://github.com/JetBrains/teamcity-docker-images/blob/master/context/generated/teamcity-server.md, though that seems to only refer to EAP, not stable.

**Comment by rickgomes-catapult** [comment]
I've just realised this, was using an AWS Linux instance, have upgraded the Java to 17 on there.  And that has sorted it, apologies for the confusion. And thanks
